<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Module;
use App\Models\Question;
use App\Models\Answer;

class HardQuestionsSeeder extends Seeder
{
    /**
     * Seed 15 hard questions per module (90 total).
     * All questions are MCQ with 4 options, difficulty=3, is_hard=true.
     * Questions are application/analysis level — not simple recall.
     */
    public function run(): void
    {
        $hardQuestions = [
            // ================================================================
            // MODULE 1: Cyber Security Essentials
            // ================================================================
            1 => [
                ['A company discovers encrypted files with a ransom note. The attack vector was an email attachment opened by an employee. Which combination of security measures would have MOST likely prevented this?', ['Email filtering with sandboxing + endpoint detection and response', 'Stronger passwords + VPN access', 'Firewall rules + antivirus signatures', 'Network segmentation + load balancing'], 0],
                ['During a penetration test, you discover that a web application reflects user input in error messages without sanitization. Which vulnerability class does this represent?', ['Reflected Cross-Site Scripting (XSS)', 'SQL Injection', 'Cross-Site Request Forgery (CSRF)', 'Server-Side Request Forgery (SSRF)'], 0],
                ['An attacker intercepts communication between a client and server by positioning themselves in the network path. They can read and modify data in transit. What type of attack is this?', ['Man-in-the-Middle (MITM) attack', 'Distributed Denial of Service (DDoS)', 'DNS poisoning', 'ARP spoofing only'], 0],
                ['A security analyst notices that a hash stored in the database matches a known hash in a rainbow table. Which password storage practice would have prevented this?', ['Salting the hash with a unique random value per user', 'Using a longer hash algorithm', 'Encrypting the hash with AES-256', 'Storing passwords in a separate database'], 0],
                ['In the context of the CIA triad, a hospital system that becomes unavailable during a ransomware attack primarily violates which principle?', ['Availability', 'Confidentiality', 'Integrity', 'Non-repudiation'], 0],
                ['An organization implements a Zero Trust security model. Which statement BEST describes this approach?', ['Never trust, always verify — every access request is authenticated regardless of network location', 'Trust internal network traffic but verify external connections', 'Trust users who have passed background checks', 'Implement maximum security restrictions on all systems equally'], 0],
                ['A web application is vulnerable to an attack where malicious SQL code is inserted through a login form. Which defence is MOST effective?', ['Parameterized queries (prepared statements)', 'Client-side input validation', 'Encoding output in HTML', 'Using HTTPS for the login page'], 0],
                ['An employee receives an email appearing to be from the CEO requesting an urgent wire transfer. The email address has a subtle misspelling. This is an example of:', ['Spear phishing with CEO fraud (whaling)', 'Generic phishing campaign', 'Vishing attack', 'Smishing attack'], 0],
                ['When analysing network traffic, a security analyst finds a large number of SYN packets without corresponding ACK packets targeting a single server. What attack is being conducted?', ['SYN Flood (TCP half-open) attack', 'UDP flood attack', 'HTTP slowloris attack', 'DNS amplification attack'], 0],
                ['A company needs to ensure that digital documents have not been tampered with during transmission. Which cryptographic mechanism should they use?', ['Digital signatures using asymmetric encryption', 'Symmetric encryption with AES', 'Base64 encoding', 'Password-protecting the document'], 0],
                ['In a buffer overflow attack, the attacker writes data beyond the allocated memory buffer. What is the primary goal of this technique?', ['Overwrite the return address to redirect execution to malicious code', 'Crash the application to cause denial of service', 'Read sensitive data from adjacent memory', 'Bypass authentication mechanisms'], 0],
                ['An IDS alert shows multiple failed login attempts from different IP addresses targeting the same account with common passwords. This pattern indicates:', ['Password spraying attack', 'Brute force attack from a single source', 'Credential stuffing attack', 'Dictionary attack with local access'], 0],
                ['Which encryption approach uses two mathematically related keys where one encrypts and the other decrypts?', ['Asymmetric (public-key) cryptography', 'Symmetric block cipher', 'Stream cipher encryption', 'Hash-based message authentication'], 0],
                ['A security audit reveals that the web application stores session tokens in URL parameters. Why is this a significant security risk?', ['Session tokens can be leaked through browser history, referrer headers, and server logs', 'URL parameters cannot be encrypted by HTTPS', 'It slows down page loading significantly', 'Users can see the session token in the browser'], 0],
                ['An organisation implements multi-factor authentication. A user provides a password and a fingerprint scan. Which factor categories are being used?', ['Something you know + something you are', 'Something you know + something you have', 'Something you have + something you are', 'Two instances of something you know'], 0],
            ],

            // ================================================================
            // MODULE 2: Cloud Computing Fundamentals
            // ================================================================
            2 => [
                ['A company needs to run a legacy application that requires specific OS configurations, but they want cloud benefits. Which cloud service model is MOST appropriate?', ['IaaS — Infrastructure as a Service', 'SaaS — Software as a Service', 'PaaS — Platform as a Service', 'FaaS — Function as a Service'], 0],
                ['An application experiences sudden traffic spikes during sales events but has minimal traffic otherwise. Which cloud feature would provide the MOST cost-effective solution?', ['Auto-scaling with pay-per-use elastic compute', 'Reserved instances with fixed capacity', 'Dedicated hosting with maximum capacity provisioned', 'On-premises servers with cloud backup'], 0],
                ['A healthcare company must comply with regulations requiring patient data to remain within national borders, but needs global availability. Which deployment strategy is MOST suitable?', ['Hybrid cloud with data residency compliance in specific regions', 'Public cloud with global replication', 'Private cloud with no external access', 'Multi-cloud with data spread across providers'], 0],
                ['In a microservices architecture deployed on cloud, Service A tries to call Service B but receives a timeout. Which pattern would BEST prevent cascading failures?', ['Circuit breaker pattern', 'Load balancer with round-robin', 'Synchronous retry with exponential backoff only', 'Direct database sharing between services'], 0],
                ['A company migrates their monolithic application to containers. During peak hours, individual containers become overwhelmed. What cloud-native solution addresses this?', ['Container orchestration with horizontal pod autoscaling (e.g., Kubernetes HPA)', 'Vertical scaling by giving containers more CPU', 'Deploying the monolith on a larger VM', 'Adding a CDN in front of the containers'], 0],
                ['An organisation uses AWS S3 for storage. They accidentally make a bucket public and customer data is exposed. This illustrates which cloud security challenge?', ['Misconfiguration of cloud resources (shared responsibility model failure)', 'Insider threat from cloud provider employees', 'Data breach due to encryption weakness', 'Denial of service attack on the storage layer'], 0],
                ['A company wants to avoid vendor lock-in while using cloud services. Which strategy would BEST achieve this?', ['Multi-cloud strategy using containerized applications with cloud-agnostic tooling', 'Using only one cloud provider to simplify management', 'Building all applications as serverless functions', 'Using proprietary managed services for better performance'], 0],
                ['When comparing cloud deployment models, which scenario BEST justifies a community cloud?', ['Multiple hospitals sharing infrastructure for HIPAA-compliant health records', 'A startup needing cheap general-purpose computing', 'A single company wanting full control over their infrastructure', 'A social media platform serving billions of users'], 0],
                ['In a cloud environment, what is the primary purpose of a Virtual Private Cloud (VPC)?', ['To create an isolated, logically-defined network within the public cloud', 'To create a private cloud within an on-premises data center', 'To encrypt all data at rest in cloud storage', 'To provide a virtual desktop environment for remote workers'], 0],
                ['A development team deploys code to production via an automated pipeline that runs tests and deploys containers. This process is called:', ['CI/CD (Continuous Integration / Continuous Deployment) pipeline', 'Infrastructure as Code provisioning', 'Blue-green deployment strategy', 'Canary release testing'], 0],
                ['An application deployed in Region A needs to failover to Region B within 15 minutes if Region A goes down. Which disaster recovery strategy is this?', ['Warm standby', 'Pilot light', 'Multi-site active-active', 'Backup and restore'], 0],
                ['A company finds that their cloud costs have increased 300% over 6 months. Investigation reveals numerous orphaned resources. Which practice would have prevented this?', ['Cloud cost governance with automated resource tagging and lifecycle policies', 'Switching to a different cloud provider', 'Migrating all workloads back to on-premises', 'Using only reserved instances'], 0],
                ['What is the key difference between horizontal scaling and vertical scaling in cloud computing?', ['Horizontal adds more instances while vertical increases resources of existing instances', 'Horizontal increases CPU/RAM while vertical adds more servers', 'They are the same concept with different names', 'Horizontal is only for databases while vertical is for applications'], 0],
                ['A serverless function processes user uploads. During a sudden burst, some invocations fail with "cold start" latency. What does "cold start" refer to?', ['The delay when a new container must be initialized because no warm instances exist', 'The time to download the function code from storage', 'Network latency between the user and the cloud region', 'Database connection pooling timeout'], 0],
                ['In cloud computing, what does the "shared responsibility model" define?', ['Which security tasks are handled by the cloud provider vs the customer', 'How costs are split between departments using cloud resources', 'How data is replicated across multiple availability zones', 'The SLA guarantees for uptime between provider and customer'], 0],
            ],

            // ================================================================
            // MODULE 3: Data Science and Analytics
            // ================================================================
            3 => [
                ['A classification model achieves 95% accuracy on a dataset where 95% of samples belong to class A. Why is accuracy misleading here?', ['The model could predict class A for everything and still achieve 95% — accuracy ignores class imbalance', 'The model is clearly excellent since 95% is a high score', 'Accuracy is never a good metric for classification', 'The training data is too large for reliable accuracy measurement'], 0],
                ['A data scientist notices that their model performs significantly better on the training set (98%) than the test set (72%). Which technique would MOST likely address this?', ['Regularization (L1/L2) and reducing model complexity', 'Training for more epochs to improve convergence', 'Adding more features to capture more patterns', 'Increasing the depth of the decision tree'], 0],
                ['When performing k-fold cross-validation with k=5, how are the training and test sets arranged across all folds?', ['Data is split into 5 equal parts — each fold uses 4 parts for training and 1 for testing, rotating the test part', 'Data is randomly split 5 times with replacement', 'The first 80% is always training and the last 20% is split into 5 test sets', 'Each fold uses a different random seed but the same train/test split'], 0],
                ['In a medical diagnosis model, a false negative (missing a disease) is far more dangerous than a false positive. Which metric should be prioritised?', ['Recall (sensitivity) — maximises detection of true positives', 'Precision — minimises false alarms', 'Accuracy — overall correctness', 'Specificity — minimises false positives'], 0],
                ['A random forest model shows that "postcode" is the most important feature for predicting income. Why might this be problematic?', ['Postcode may act as a proxy for race/ethnicity, introducing algorithmic bias', 'Postcodes have too many unique values for tree models', 'The model will overfit to specific postcodes', 'Random forests cannot handle categorical features'], 0],
                ['The confusion matrix for a binary classifier shows: TP=80, FP=20, FN=30, TN=870. Calculate the precision.', ['0.80 (80/100)', '0.73 (80/110)', '0.97 (950/980)', '0.89 (870/980)'], 0],
                ['A data scientist applies PCA to a 50-feature dataset and keeps components explaining 95% of variance, resulting in 8 components. What has PCA achieved?', ['Dimensionality reduction from 50 to 8 features while preserving 95% of information', 'Feature selection — keeping the 8 best original features', 'Data augmentation — creating 8 new synthetic features', 'Data normalization — scaling all features to unit variance'], 0],
                ['When training a neural network, the loss decreases for the first 50 epochs then starts increasing on the validation set while continuing to decrease on training. This indicates:', ['Overfitting — the model memorises training data after epoch 50', 'Underfitting — the model is too simple', 'The learning rate is too low', 'The batch size is too large'], 0],
                ['An e-commerce company wants to group customers by purchasing behaviour without predefined categories. Which approach is MOST appropriate?', ['Unsupervised clustering (e.g., K-Means or DBSCAN)', 'Supervised classification with logistic regression', 'Linear regression on purchase amounts', 'Time series forecasting'], 0],
                ['A dataset contains a feature "salary" ranging from 20,000-200,000 and "age" ranging 18-65. Why might StandardScaler be applied before training a KNN model?', ['KNN uses distance metrics — unscaled features with larger ranges dominate distance calculations', 'KNN requires normally distributed features', 'StandardScaler improves model accuracy regardless of algorithm', 'It prevents overfitting in distance-based models'], 0],
                ['The ROC curve for Model A has an AUC of 0.92, while Model B has AUC of 0.78. What does this comparison tell us?', ['Model A has better overall discrimination ability across all classification thresholds', 'Model A is 14% more accurate than Model B', 'Model A has fewer false positives at every threshold', 'Model B is underfitting while Model A is not'], 0],
                ['A gradient boosting model produces SHAP values for each prediction. A student has a positive SHAP value (+0.15) for score_percentage. What does this mean?', ['The student\'s score pushed the prediction toward a higher mastery level compared to the average', 'The student scored 15% higher than average', 'The feature is 15% important to the model', 'The model is 15% confident about this prediction'], 0],
                ['When evaluating a multi-class classifier with 4 classes, which averaging method for F1-score gives equal weight to each class regardless of support?', ['Macro average — averages per-class F1 scores equally', 'Weighted average — weights by class support', 'Micro average — aggregates TP/FP/FN globally', 'Binary average — only considers two classes'], 0],
                ['A decision tree has depth=20 and perfectly classifies all training examples. When deployed, it performs poorly on new data. Which approach would NOT help?', ['Increasing tree depth to 30 for better pattern capture', 'Pruning the tree to reduce depth', 'Using ensemble methods like Random Forest', 'Applying min_samples_leaf constraints'], 0],
                ['Feature importance from a tree model shows "student_id" is highly predictive. Why should this feature be removed?', ['student_id is a unique identifier with no generalizable predictive pattern — it leads to data leakage/memorization', 'student_id values are too large for trees to split on', 'It violates privacy regulations to use student IDs', 'Tree models cannot process integer-type features'], 0],
            ],

            // ================================================================
            // MODULE 4: Network Infrastructure
            // ================================================================
            4 => [
                ['A network has the subnet 192.168.10.0/26. How many usable host addresses are available?', ['62', '64', '126', '30'], 0],
                ['A switch receives a frame with a destination MAC address not in its MAC address table. What does it do?', ['Floods the frame out all ports except the source port', 'Drops the frame silently', 'Sends an ARP request to find the destination', 'Forwards it to the default gateway'], 0],
                ['An administrator needs to isolate departments on the same physical switch into separate broadcast domains. Which technology should they use?', ['VLANs (Virtual Local Area Networks)', 'Subnetting at the router only', 'Port mirroring', 'Link aggregation (LACP)'], 0],
                ['A company uses NAT on their router. Internal hosts use 10.0.0.0/8 addresses. Why can these addresses not be routed on the public internet?', ['10.0.0.0/8 is an RFC 1918 private address range — routers on the internet drop these packets', 'The addresses are too long for routing tables', 'ISPs block all traffic from the 10.x.x.x range', 'NAT only works with public IP addresses'], 0],
                ['During a traceroute, an administrator notices that hop 5 shows significantly higher latency than surrounding hops. What does this MOST likely indicate?', ['Congestion or a bottleneck at the router at hop 5', 'A physical cable fault between hop 4 and 5', 'The destination server is at hop 5', 'A DNS resolution failure at that hop'], 0],
                ['A client sends a DHCP Discover message. Why is this sent as a broadcast?', ['The client does not yet have an IP address and does not know the DHCP server address', 'DHCP always uses broadcast for security', 'Broadcast is faster than unicast for DHCP', 'The DHCP server requires broadcast messages'], 0],
                ['In the OSI model, which layer is responsible for establishing, managing, and terminating connections between applications?', ['Session layer (Layer 5)', 'Transport layer (Layer 4)', 'Application layer (Layer 7)', 'Presentation layer (Layer 6)'], 0],
                ['A network administrator configures a static route with an administrative distance of 1. A routing protocol discovers the same route with AD of 110. Which route is used?', ['The static route (AD=1) because lower administrative distance is preferred', 'The dynamic route (AD=110) because it was discovered automatically', 'Both routes are used for load balancing', 'Neither — the router will drop packets due to conflict'], 0],
                ['A host with IP 172.16.5.100/24 tries to communicate with 172.16.10.50/24. Why must this traffic go through a router?', ['The hosts are on different subnets (172.16.5.x vs 172.16.10.x) and need Layer 3 routing', 'The IP addresses are in different private ranges', 'Switches cannot forward traffic between these addresses', 'The subnet mask /24 only allows 254 local hosts'], 0],
                ['In a TCP three-way handshake, what is the correct sequence of segments exchanged?', ['SYN → SYN-ACK → ACK', 'SYN → ACK → SYN-ACK', 'ACK → SYN → SYN-ACK', 'SYN → SYN → ACK'], 0],
                ['A DNS query for "example.com" returns an A record pointing to 93.184.216.34, but also includes an additional AAAA record. What does the AAAA record provide?', ['The IPv6 address for the same domain', 'An alias pointing to another domain name', 'The authoritative name server address', 'A mail exchange server address'], 0],
                ['An administrator configures port security on a switch to allow only 2 MAC addresses per port. A third device is connected. What happens with "violation mode shutdown"?', ['The port is disabled (err-disabled state) and must be manually re-enabled', 'The third device\'s traffic is simply dropped', 'All three devices lose connectivity', 'The switch sends a notification but allows all traffic'], 0],
                ['What is the primary purpose of the Spanning Tree Protocol (STP) in a switched network?', ['To prevent switching loops by blocking redundant paths while maintaining failover capability', 'To encrypt traffic between switches', 'To balance traffic load across all switch ports', 'To assign VLANs to switch ports automatically'], 0],
                ['A company has offices in two cities connected via the internet. They need secure, private communication. Which technology creates an encrypted tunnel between the sites?', ['Site-to-site VPN using IPSec', 'Port forwarding on the edge router', 'VLAN trunking between the offices', 'BGP peering between the ISPs'], 0],
                ['A packet capture shows a device sending an ARP request asking "Who has 192.168.1.1?" but the source IP is also 192.168.1.1. What is this device doing?', ['Gratuitous ARP — checking for IP address conflicts or announcing its presence', 'ARP spoofing attack', 'Normal ARP resolution for the gateway', 'Broadcasting its MAC address for all hosts'], 0],
            ],

            // ================================================================
            // MODULE 5: IT Project Management
            // ================================================================
            5 => [
                ['A project is 60% complete with a budget of £100,000. So far, £70,000 has been spent, but only £50,000 worth of work has been completed. What is the Cost Performance Index (CPI)?', ['0.71 (EV/AC = 50,000/70,000)', '1.40 (AC/EV = 70,000/50,000)', '0.83 (EV/BAC = 50,000/60,000)', '1.17 (AC/PV = 70,000/60,000)'], 0],
                ['During sprint planning, the team estimates a user story at 13 story points — much higher than similar stories. The Product Owner insists it must be in this sprint. What should the Scrum Master recommend?', ['Break the story into smaller, independently deliverable stories that fit the sprint', 'Extend the sprint duration to accommodate the large story', 'Add more team members to complete it faster', 'Skip estimation and just commit to completing it'], 0],
                ['A project manager identifies a risk that a key developer might leave during the project. They arrange for another developer to shadow the key person. This risk response is:', ['Risk mitigation — reducing the probability or impact of the risk', 'Risk avoidance — eliminating the risk entirely', 'Risk transfer — shifting the risk to a third party', 'Risk acceptance — acknowledging without action'], 0],
                ['In a Kanban board, the "Testing" column has a WIP (Work In Progress) limit of 3, but there are already 3 items there. A developer finishes coding a new feature. What should happen?', ['The developer should help clear items from Testing before pulling new work into development', 'The WIP limit should be temporarily increased to 4', 'The new item should be placed in a waiting queue between columns', 'The developer should start working on the next backlog item'], 0],
                ['A stakeholder requests a new feature mid-project that was not in the original scope. The project uses Waterfall methodology. What is the MOST appropriate first step?', ['Submit a formal change request through the change control process', 'Add it to the current phase since the stakeholder is important', 'Reject it since Waterfall does not allow changes', 'Add it to the next project release'], 0],
                ['The MoSCoW method categorises requirements as Must, Should, Could, Won\'t. A project has limited time. Which category should be delivered first to ensure project success?', ['Must Have — critical requirements without which the project fails', 'Should Have — important but not critical requirements', 'Could Have — nice-to-have features', 'All categories should receive equal priority'], 0],
                ['A burndown chart shows that the remaining work line is consistently above the ideal line throughout the sprint. What does this indicate?', ['The team is behind schedule and unlikely to complete all sprint items', 'The team is ahead of schedule', 'The sprint scope has been reduced', 'The team velocity is increasing'], 0],
                ['A project team uses velocity averaging. Their last 3 sprints had velocities of 30, 35, and 25 story points. What should their commitment be for the next sprint?', ['30 story points (average of last 3 sprints)', '35 story points (highest achieved)', '25 story points (most conservative estimate)', '45 story points (to push the team)'], 0],
                ['In the iron triangle of project management, if the scope increases but budget and time remain fixed, what is the MOST likely impact?', ['Quality will decrease', 'The project will automatically get more resources', 'The timeline extends proportionally', 'No impact if the team works harder'], 0],
                ['A retrospective reveals that integration issues are discovered late in each sprint. Which practice would BEST address this?', ['Continuous Integration with automated testing on every code commit', 'More thorough code reviews at the end of each sprint', 'Extending the sprint by one week for integration', 'Assigning a dedicated integration team'], 0],
                ['What distinguishes a product roadmap from a project plan?', ['A roadmap shows strategic direction and high-level goals over time while a project plan details specific tasks and timelines', 'A roadmap is used in Agile while a project plan is only for Waterfall', 'A roadmap is created by developers while a project plan is for managers', 'There is no meaningful difference between the two'], 0],
                ['A critical path analysis shows the project has zero float on the path A→C→E→G. If task C is delayed by 2 days, what is the impact?', ['The entire project is delayed by 2 days', 'Only subsequent tasks on alternative paths are affected', 'The project absorbs the delay using total float', 'Task G can start earlier to compensate'], 0],
                ['A team practices pair programming. Which is a primary benefit of this approach?', ['Real-time code review and knowledge sharing, reducing defects', 'It doubles development speed', 'It replaces the need for unit testing', 'It eliminates the need for a code repository'], 0],
                ['A project uses earned value management. EV = £40,000, PV = £50,000, AC = £45,000. What is the Schedule Performance Index (SPI)?', ['0.80 (EV/PV = 40,000/50,000) — behind schedule', '0.89 (EV/AC = 40,000/45,000) — over budget', '1.11 (PV/AC = 50,000/45,000) — under budget', '1.25 (PV/EV = 50,000/40,000) — ahead of schedule'], 0],
                ['An Agile team has a Product Owner who frequently changes priorities mid-sprint, causing disruption. What is the BEST course of action?', ['The Scrum Master should protect the sprint commitment and defer changes to the next sprint planning', 'The team should accommodate all changes to satisfy the Product Owner', 'The sprint should be cancelled and replanned', 'Priority changes should be handled by the development manager'], 0],
            ],

            // ================================================================
            // MODULE 6: Software Engineering Principles
            // ================================================================
            6 => [
                ['A developer notices that changing a single function causes 15 unit tests to fail across different modules. This is a symptom of:', ['Tight coupling between modules — the function has too many dependencies', 'Good test coverage detecting real bugs', 'Over-testing — too many tests for one function', 'Insufficient abstraction in the test framework'], 0],
                ['In SOLID principles, the "O" stands for Open/Closed Principle. What does this mean in practice?', ['Classes should be open for extension but closed for modification — use inheritance/composition instead of changing existing code', 'Only open-source software should be used', 'Methods should be open to multiple parameter types', 'Classes should always be open for any modifications'], 0],
                ['A team refactors a monolithic application into microservices. Which challenge is MOST likely to emerge?', ['Distributed system complexity — network latency, data consistency, service discovery, and debugging across services', 'Reduced code reuse across services', 'Inability to deploy services independently', 'Higher memory usage per service'], 0],
                ['A code review reveals the following: a class has methods for user authentication, email sending, PDF generation, and database queries. Which SOLID principle is being violated?', ['Single Responsibility Principle — the class has too many unrelated responsibilities', 'Liskov Substitution Principle', 'Interface Segregation Principle', 'Dependency Inversion Principle'], 0],
                ['A development team implements the Repository Pattern. What is the PRIMARY benefit?', ['Abstracts data access logic, making it easier to switch storage backends or test with mock data', 'Increases database query performance', 'Eliminates the need for an ORM', 'Ensures data is always cached in memory'], 0],
                ['In Test-Driven Development (TDD), what is the correct sequence of steps?', ['Write a failing test → Write minimal code to pass → Refactor (Red-Green-Refactor)', 'Write code → Write tests → Refactor', 'Refactor existing code → Write tests → Deploy', 'Write all tests first → Write all code → Run all tests'], 0],
                ['A Git repository has branches: main, develop, feature/login, and hotfix/security-patch. This structure follows which branching strategy?', ['Git Flow — separate branches for features, development, releases, and hotfixes', 'Trunk-based development', 'GitHub Flow with feature branches', 'Forking workflow'], 0],
                ['A function calculates a discount: it reads the customer type from a global variable, queries the database for pricing rules, sends an analytics event, and returns the discount. What design principle does this violate?', ['Separation of Concerns — the function mixes business logic, data access, and side effects', 'DRY — the function repeats code', 'YAGNI — the function adds unneeded features', 'KISS — the function is not simple enough'], 0],
                ['An API endpoint returns user data including password hashes in the JSON response. Beyond the obvious security issue, which REST API design principle is this violating?', ['Principle of Least Privilege / minimal disclosure — only return data the client needs', 'Statelessness — the server maintains session state', 'Uniform Interface — inconsistent response format', 'HATEOAS — missing hypermedia controls'], 0],
                ['A developer uses dependency injection in a controller: __construct(UserRepository $repo). What is the primary advantage over new UserRepository() inside the method?', ['The dependency can be easily swapped (e.g., for testing with a mock), promoting loose coupling', 'It improves runtime performance', 'It reduces the number of classes needed', 'It automatically handles database transactions'], 0],
                ['A continuous integration pipeline fails at the "lint" stage. What does this stage check?', ['Code style, formatting, and static analysis errors without executing the code', 'Whether the application compiles successfully', 'Whether all unit tests pass', 'Whether the deployment to staging succeeds'], 0],
                ['A team implements the Observer Pattern in their notification system. When an order is placed, email, SMS, and push notification services are automatically triggered. What is the key benefit?', ['New notification channels can be added without modifying the order processing code (loose coupling)', 'All notifications are guaranteed to arrive in order', 'The pattern eliminates the need for message queues', 'It makes the system synchronous and predictable'], 0],
                ['What is the primary difference between unit tests and integration tests?', ['Unit tests verify individual components in isolation while integration tests verify interactions between components', 'Unit tests are faster but less reliable than integration tests', 'Integration tests mock all dependencies while unit tests use real ones', 'Unit tests are for backend code only while integration tests are for frontend'], 0],
                ['A REST API uses HTTP status code 201 after successfully creating a resource. Which response code should be returned when the client sends malformed JSON?', ['400 Bad Request', '404 Not Found', '500 Internal Server Error', '422 Unprocessable Entity'], 0],
                ['An application uses an MVC architecture. A developer places database query logic directly in a Blade view template. Why is this problematic?', ['It violates separation of concerns — views should only handle presentation, not data access', 'Blade templates cannot execute PHP code', 'It will cause SQL injection vulnerabilities', 'MVC requires all queries in the Model only'], 0],
            ],
        ];

        foreach ($hardQuestions as $moduleId => $questions) {
            $module = Module::find($moduleId);
            if (!$module) continue;

            $this->command->info("Seeding hard questions for: {$module->name}");

            foreach ($questions as [$questionText, $answers, $correctIndex]) {
                $question = Question::create([
                    'question_text' => $questionText,
                    'type' => 'mcq',
                    'module_id' => $moduleId,
                    'difficulty' => 3,
                    'is_hard' => true,
                ]);

                foreach ($answers as $index => $answerText) {
                    Answer::create([
                        'question_id' => $question->id,
                        'answer_text' => $answerText,
                        'is_correct' => $index === $correctIndex,
                    ]);
                }
            }
        }

        $this->command->info("✅ Seeded 15 hard questions per module (90 total) for all 6 modules!");
    }
}
